// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import charlie "github.com/Bhinneka/alpha/api/service/domain/v1/charlie"
import mock "github.com/stretchr/testify/mock"
import mongo "go.mongodb.org/mongo-driver/mongo"

// MongoDB is an autogenerated mock type for the MongoDB type
type MongoDB struct {
	mock.Mock
}

// InsertCharlieHistory provides a mock function with given fields: db, param
func (_m *MongoDB) InsertCharlieHistory(db *mongo.Database, param charlie.Domain) {
	_m.Called(db, param)
}
